<?php

/**
 * @file
 * Bootstrap sub-theme.
 *
 * Place your custom PHP code in this file.
 */

function customtheme_preprocess_html(&$variables) {
  $node = \Drupal::routeMatch()->getParameter('node');
  $node_id = $node->id();
  if ($node instanceof \Drupal\node\NodeInterface && ($node_id % 2 == 0)) {
    $variables['attributes']['class'][] = 'day';
  }
  if ($node instanceof \Drupal\node\NodeInterface && !($node_id % 2 == 0)) {
    $variables['attributes']['class'][] = 'night';
  }
}
